### ISSUE TITLE
getting error when installing

### ISSUE THREAD

**Issue by techsaqib** [svdo/ipatool#7]
Hi , i am trying to install your toll but getting an error 

The following build commands failed:
	Ld /var/root/Library/Developer/Xcode/DerivedData/ipatool-guctflnmoxchhsemrjowdfwxiyig/Build/Intermediates/ArchiveIntermediates/ipatool/InstallationBuildProductsLocation/usr/local/bin/ipatool normal x86_64

please reply as soon as possible

**Comment by svdo** [comment]
Hi @techsaqib, I'll have a quick look to see if I can reproduce and easily solve.

In the mean time I'd like to know what it is that you like most about ipatool. I'm asking because I haven't worked on this a long time now, and I think there are a number of alternatives. In other words: what is it about ipatool that makes you choose it over other options?

**Comment by svdo** [comment]
I have pushed some updates and repairs. Please try again. I'd still be interested in your answer to my question above, thanks!

**Comment by techsaqib** [comment]
thanks i will try and let u know
